on:
    schedule:
    - cron: '0 */12 * * *'
    
jobs:
    build:
        runs-on: ubuntu-24.04
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                color: [0, 1, 2, 3]
        steps:
        - run: |
              podman run --init -d -e RP_EMAIL=chaowen.guo1@gmail.com -e RP_API_KEY=9b23ebb9-2ee1-427f-a271-f6fdf536537b docker.io/repocket/repocket
              sudo apt update
              curl -o alexamaster.mjs https://dev.azure.com/chaowenguo/ci/_apis/git/repositories/ci/items?path=alexamaster.mjs
              awk -i inplace /'const id = 535'/{sub\(/'const id = 535'/\,\"'const id = 1092'\"\)}1 alexamaster.mjs
              npm install patchright tough-cookie git+https://github.com/chaowenguo/tlsclient.js
              while true
              do 
                  node alexamaster.mjs
              done
    clean:
        runs-on: ubuntu-24.04
        permissions:
            actions: write
        steps:
        - run: |
              sudo apt update
              sudo apt install -y --no-install-recommends python3-aiohttp
              curl https://bitbucket.org/chaowenguo/common/raw/main/clean.py | python3 - ${{secrets.GITHUB_TOKEN}}
